### ISSUE TITLE
controller.registerEventListeners is not a function

### ISSUE THREAD

**Issue by kalebheitzman** [brunobaudry/moodle-local_deepler#50]
Just tried the latest code from main and ran into this:

```
Uncaught TypeError: controller.registerEventListeners is not a function
    at translate.php?courseid=848&lang=en&target_lang=pl:16499:16
    at Object.execCb (require.min.js:5:12861)
    at b.check (require.min.js:5:6615)
    at b.enable (require.min.js:5:9363)
    at b.init (require.min.js:5:5721)
    at require.min.js:5:11235
```

It's successfully pulling translations but not saving it to the database. The error message returned gets returned as:

```
[object object]
```

The response from service:

```
[
    {
        "error": true,
        "exception": {
            "message": "Invalid response value detected",
            "errorcode": "invalidresponse",
            "link": "https:\/\/moodlesite\/local\/deepler\/translate.php?courseid=848&lang=en&target_lang=pl",
            "moreinfourl": "https:\/\/docs.moodle.org\/404\/en\/error\/debug\/invalidresponse"
        }
    }
]
```

Some items seem to translate and save fine, but many don't. I might be able to get into the code and debug the last week of December.

**Comment by brunobaudry** [comment]
Hi @kalebheitzman, do you still got that error ?
